# Generated by Django 6.0.2 on 2026-02-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_order_store_orderitem_product_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Açık Sipariş'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_orders', to='main.store', verbose_name='Masa'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('table', 'is_open')},
        ),
    ]
