# Generated by Django 6.0.2 on 2026-02-23 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_is_open_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='main.store'),
        ),
        migrations.AlterField(
            model_name='userstore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
    ]
