# Generated by Django 6.0.2 on 2026-02-23 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_table_store_alter_userstore_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_store', to=settings.AUTH_USER_MODEL),
        ),
    ]
