# Generated by Django 6.0.2 on 2026-02-25 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='main.order')),
            ],
            options={
                'verbose_name': 'Sipariş İstemi',
                'verbose_name_plural': 'Sipariş İstemleri',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='main.orderticket'),
        ),
    ]
