# Generated by Django 6.0.2 on 2026-02-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_orderticket_orderitem_ticket'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
