# Generated by Django 6.0.2 on 2026-02-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
