# Generated by Django 6.0.2 on 2026-02-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Sipariş Kalemi', 'verbose_name_plural': 'Sipariş Kalemleri'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
