# Generated by Django 6.0.2 on 2026-02-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_orderitem_options_orderitem_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
