# Generated by Django 6.0.2 on 2026-02-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_orderticket_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_canceled',
        ),
    ]
