# Generated by Django 6.0.2 on 2026-03-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_orderitem_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
