# Generated by Django 6.0.2 on 2026-03-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_is_printed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
