# Generated by Django 6.0.2 on 2026-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_order_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('table',), name='unique_open_order_per_table'),
        ),
    ]
