# Generated by Django 6.0.2 on 2026-03-05 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order_unique_open_order_per_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL),
        ),
    ]
