# Generated by Django 6.0.2 on 2026-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_userstore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='display',
            field=models.CharField(choices=[('cds', 'CDS'), ('kds', 'KDS'), ('wds', 'WDS'), ('mds', 'mds')], default='cds', max_length=3, verbose_name='Görüntüleme'),
        ),
    ]
