# Generated by Django 6.0.2 on 2026-03-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_userstore_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='display',
            field=models.CharField(choices=[('wds', 'WDS'), ('kds', 'KDS'), ('mds', 'mds')], default='wds', max_length=3, verbose_name='Görüntüleme'),
        ),
    ]
